spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: 1.0
accounts:
  message: "This is the prod profile"
  contact:
    name: "This developer name from prod env"
    email: "prod@mail.com"
  contactNumbers:
    - "738328272"
    - "372828375"
